MinecraftCubed.Web/ViewModels/User_/UserNavModel.cs
using System.Collections.Generic;
using MinecraftCubed.Domain.Models;
using MinecraftCubed.Domain.Models.Responses;

namespace MinecraftCubed.Web.ViewModels.User_
{
    public class UserNavModel
    {
        public string Username { get; set; }
        public string FaceUrl { get; set; }
        public ICollection<NameAndIdentifier> ManagedServers { get; set; }
        public ICollection<NameAndIdentifier> ManagedEvents { get; set; }
    }
}

MinecraftCubed.Web/Controllers/AuthController.cs
using System;
using System.Data.Entity.Migrations.Sql;
using System.Diagnostics;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using System.Web.UI;
using CaptchaMvc.Attributes;
using MinecraftCubed.Common;
using MinecraftCubed.Domain.Azure;
using MinecraftCubed.Domain.Redis;
using MinecraftCubed.Domain.Redis.Extensions;
using MinecraftCubed.Static;
using MinecraftCubed.Common.Extensions.Capture;
using MinecraftCubed.Common.Helpers;
using MinecraftCubed.Common.Lang;
using MinecraftCubed.Minecraft;
using MinecraftCubed.Service.Services.Interfaces;
using MinecraftCubed.Web.Mvc.Attributes;
using MinecraftCubed.Web.ViewModels.Auth;
using MinecraftCubed.Web.ViewModels.Email;

namespace MinecraftCubed.Web.Controllers
{
    public class AuthController : BaseController
    {
        private readonly IAuthService _authService;
        private readonly IUserService _userService;

        public AuthController(IAuthService authService, IUserService userService)
        {
            _authService = authService;
            _userService = userService;
        }

        [HttpPost]
        public JsonResult Status()
        {
            return Json(new { authenticated = Request.IsAuthenticated });
        }
        
        [Route("logout")]
        public ActionResult Logout()
        {
            _authService.LogOut();
            return Redirect("~/");
        }

        [HttpPost]
        public void LogoutAsync()
        {
            _authService.LogOut();
        }

        [HttpGet]
        [OutputCache(Duration = 60)]
        public PartialViewResult LoginAsync()
        {
            return PartialView(new LoginModel());
        }

        [HttpPost]
        public PartialViewResult LoginAsync(LoginModel model)
        {
            if (!model.AllowProcess)
            {
                return PartialView(model);
            }

            // forgot password form does not care about password validation errors

            if (model.IsForgotPass)
            {
                ModelState.Remove("Password");
            }

            // check that it is an email or username (16 chars)

            if (!ValidationHelper.IsEmail(model.UserOrEmail))
            {
                if (!ValidationHelper.IsAlphanumeric(model.UserOrEmail) || model.UserOrEmail.Trim().Length > 16)
                {
                    ModelState.AddModelError("UserOrEmail", Messages.BadEmailOrUser);
                }
            }

            // errors in model

            if (!ModelState.IsValid)
            {
                return PartialView(model);
            }

            if (model.IsForgotPass)
            {
                // handle forgot pass

                var user = _userService.GetUserByEmail(model.UserOrEmail);

                if (user != null)
                {
                    // limit 3 sends every five minutes by ip
                    
                    var sent = RuntimeCache.GetOrStore(Constant.Cache.ForgotEmailLimit + UserHelper.GetIp(), 0, TimeSpan.FromMinutes(5));

                    if (sent > 3)
                    {
                        return PartialView("_ForgotPassWait");
                    }
                    
                    RuntimeCache.Store(Constant.Cache.ForgotEmailLimit + UserHelper.GetIp(), ++sent, TimeSpan.FromMinutes(5));
                    
                    var code = _userService.RenewConfirmationCode(model.UserOrEmail);

                    var body = View("ForgotPass", new ForgotPassModel
                    {
                        Email = HttpUtility.UrlEncode(user.Email),
                        Username = HttpUtility.UrlEncode(user.Username),
                        ConfirmationCode = HttpUtility.UrlEncode(code)
                    }).Capture(ControllerContext);

                    MailHelper.SendForgotPassEmail(user.Email, body);

                    return PartialView("_ForgotPassDone");
                }

                ModelState.AddModelError("Error", Messages.EmailNotFound);
            }
            else
            {
                // handle login

                var user = _authService.LogIn(model.UserOrEmail, model.Password);

                if (user != null)
                {
                    // limit 3 sends every five minutes by ip

                    var sent = RuntimeCache.GetOrStore(Constant.Cache.LoginLimit + UserHelper.GetIp(), 0, TimeSpan.FromMinutes(30));

                    if (sent > 15)
                    {
                        RedisStore.Current.Remove(Constant.Cache.LoginLimit);
                        return PartialView("_LoginWait");
                    }

                    RuntimeCache.Store(Constant.Cache.LoginLimit + UserHelper.GetIp(), ++sent, TimeSpan.FromMinutes(5));

                    FormsAuthentication.SetAuthCookie(user.Username, Settings.PersistLogin);

                    RedisStore.Current.Remove(Constant.MCUsername);
                    
                    return PartialView("_LoginDone", new AuthModel
                    {
                        Username = user.Username
                    });
                }

                user = _userService.GetUser(model.UserOrEmail);

                if (user != null)
                {
                    ModelState.AddModelError("Error", Messages.WrongPassword);
                    return PartialView(model);
                }

                ModelState.AddModelError("Error", Messages.EmailOrUserNotFound);
            }

            return PartialView(model);
        }

        [HttpGet]
        public PartialViewResult RegisterAsync()
        {
            return PartialView(new RegisterModel());
        }

        [HttpPost]
        [CaptchaVerify("Incorrect CAPTCHA code!")]
        public PartialViewResult RegisterAsync(RegisterModel model)
        {
            if (!model.AllowProcess)
            {
                return PartialView(model);
            }

            // errors in model

            if (!ModelState.IsValid)
            {
                return PartialView(model);
            }
            
            // email exists

            if (_userService.ExistsEmail(model.Email))
            {
                ModelState.AddModelError("Error", Messages.EmailAlreadyRegistered);
                return PartialView(model);
            }
            
            // pick up username from input

            var username = model.Username;
            
            // username exists

            if (_userService.ExistsUsername(username))
            {
                ModelState.AddModelError("Error", Messages.UserAlreadyRegistered);
                return PartialView(model); 
            }

            // create the user

            var user = _userService.CreateUser(model.Email, username, model.NewPassword, null, false);

            // log him in

            FormsAuthentication.SetAuthCookie(user.Username, Settings.PersistLogin);

            Task.Run(() => _userService.SaveMinecraftHead(user.Username));

            return PartialView("_RegisterDone", new AuthModel
            {
                Username = user.Username
            });
        }

        [HttpPost]
        [Route("auth/verifyendpoint/{key}/{uuid}/{username}")]
        public bool VerifyEndpoint(string username, string uuid, string key)
        {
            try
            {
                if (key == Constant.LoginVerifySecret)
                {
                    _userService.UpdateVerifiedAccount(username, uuid);
                    _userService.SaveMinecraftHead(username);
                    return true;
                }
            }
            catch (Exception ex)
            {
                Trace.TraceError("Verify Endpoint Fail: " + ex.Message);
                return false;
            }

            return true;
        }

        [HttpGet]
        [OutputCache(NoStore = true, Location = OutputCacheLocation.None)]
        public ActionResult ChangePass(string email, string code)
        {
            var verified = _userService.VerifyConfirmationCode(email, code);

            if (verified)
            {
                return View(new ChangePassModel
                {
                    Email = email,
                    Code = code
                });
            }

            ModelState.AddModelError("Error", Messages.TheCodeHasExpired);
            return View(new ChangePassModel());
        }

        [HttpPost]
        [OutputCache(NoStore = true, Location = OutputCacheLocation.None)]
        public ActionResult ChangePass(ChangePassModel model)
        {
            if (ModelState.IsValid)
            {
                var verified = _userService.VerifyConfirmationCode(model.Email, model.Code);

                if (!verified)
                {
                    ModelState.AddModelError("Error", Messages.TheCodeHasExpired);
                    return View(model);
                }

                _userService.ChangeUserPassword(model.Email, model.Password);
                return View("ChangePassDone");
            }

            return View(model);
        }

        [OutputCache(NoStore = true, Location = OutputCacheLocation.None)]
        public ActionResult Sso(string sso, string sig)
        {
            if (string.IsNullOrEmpty(sso) || string.IsNullOrEmpty(sig))
                return Content("Invalid");

            var checksum = Utils.GetHash(sso, Constant.SSOSecret);
            if (checksum != sig)
                return Content("Invalid");

            var ssoBytes = Convert.FromBase64String(sso);
            var decodedSso = Encoding.UTF8.GetString(ssoBytes);
            var nvc = HttpUtility.ParseQueryString(decodedSso);
            var nonce = nvc["nonce"];

            var user = _userService.GetCurrentUserCached();

            if (user == null)
            {
                return Redirect(Constant.DiscourseURL);
            }

            var email = user.Email;

MinecraftCubed.Web/Controllers/ServerController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using MinecraftCubed.Common;
using MinecraftCubed.Common.Extensions;
using MinecraftCubed.Common.Helpers;
using MinecraftCubed.Domain.Redis;
using MinecraftCubed.Minecraft;
using MinecraftCubed.Static;
using MinecraftCubed.Domain.Models.Page;
using MinecraftCubed.Service.Services.Interfaces;
using MinecraftCubed.Web.Mvc;
using MinecraftCubed.Web.Mvc.Attributes;
using MinecraftCubed.Web.ViewModels.List;

namespace MinecraftCubed.Web.Controllers
{
    //[LightMenu]
    public class ServerController : Controller
    {
        private readonly IServerService _serverService;
        private readonly IUserService _userService;
        private readonly IChatService _chatService;
        private readonly IStaffService _staffService;
        private readonly ISponsorService _sponsorService;

        public ServerController(IServerService serverService, IUserService userService, IStaffService staffService, IChatService chatService, ISponsorService sponsorService)
        {
            _serverService = serverService;
            _userService = userService;
            _staffService = staffService;
            _chatService = chatService;
            _sponsorService = sponsorService;
        }

        [Route("server/{identifier}")]
        public ActionResult Index(string identifier)
        {
            var server = _serverService.GetServerByIdentifier(identifier);

            if (server == null)
            {
                return RedirectToAction("Status404", "Home");
            }

            // compile page server data

            var model = new ServerPageModel
            {
                PageServer = RedisStore.Current.GetOrStore(Constant.Cache.PageServer + server.Identifier, () => _serverService.BuildPageServer(identifier), TimeSpan.FromSeconds(30), RedisDatabase.BuiltObjects)
            };
          
            return View(model);
        }

        [Route("serverdata/{identifier}")]
        public JsonResult GetServerData(string identifier)
        {
            var server = _serverService.GetServerByIdentifier(identifier);

            if (server == null)
            {
                return Json(new {});
            }
            
            // compile page data

            var data = RedisStore.Current.GetOrStore(Constant.Cache.PageData + server.Identifier, () => _serverService.BuildPageData(identifier), TimeSpan.FromSeconds(30));
            
            // add in non-cachable data

            var user = _userService.GetCurrentUser();

            if (user != null)
            {
                var isSysAdmin = user.HasRole(UserRole.SysAdmin);

                data.IsManager = isSysAdmin || _staffService.IsServerManager(identifier, user.Username);
                data.IsAdmin = isSysAdmin || _staffService.IsServerAdmin(identifier, user.Username);
                data.IsStaff = isSysAdmin || _staffService.IsServerStaff(identifier, user.Username);
                data.Color = _staffService.GetColor(identifier, user.Username);
            }

            // add in messages

            var msgs = _chatService.GetChat(server, 0, 100);

            data.InitialChat = msgs;
            data.Logged = Request.IsAuthenticated;
            data.Verified =  user != null && user.HasRole(UserRole.User);
            data.Username = user != null ? user.Username : string.Empty;

            // serialize

            return new JsonNetResult
            {
                Data = data
            };
        }
    }
}

MinecraftCubed.Web/Controllers/UserController.cs
using System.Linq;
using System.Web.Mvc;
using MinecraftCubed.Service.Services.Interfaces;
using MinecraftCubed.Web.Mvc.Attributes;
using MinecraftCubed.Web.ViewModels.User_;


namespace MinecraftCubed.Web.Controllers
{
    public class UserController : BaseController
    {
        private readonly IUserService _userService;
        private readonly IStaffService _staffService;

        public UserController(IUserService userService, IStaffService staffService)
        {
            _userService = userService;
            _staffService = staffService;
        }

        public ActionResult Index()
        {
            return RedirectToAction("Index", "List");
        }

        public JsonResult GetCurrentUsername()
        {
            var user = _userService.GetCurrentUserCached();

            if (user != null)
            {
                return Json(user.Username);
            }
            return null;
        }

        [ChildActionOnly]
        public PartialViewResult UserNav()
        {
            // if not authenticated show the button

            if (!Request.IsAuthenticated)
            {
                return PartialView("LoginButton");
            }

            // otherwise show the user nav

            var user = _userService.GetCurrentUserCached();
            var servers = _staffService.GetManagedServerList();
            var events = _staffService.GetManagedEventList();
        
            var model = new UserNavModel
            {
                ManagedServers = servers,
                ManagedEvents = events
            };

            if (user != null)
            {
                model.Username = user.Username;
                model.FaceUrl = user.GetFaceUrl();
            }

            return PartialView(model);
        }

        [ChildActionOnly]
        public PartialViewResult SettingsNav()
        {
            return PartialView();
        }

        [ChildActionOnly]
        public PartialViewResult EventSettingsNav()
        {
            return PartialView();
        }
    }
}

MinecraftCubed.Web/Views/User/EventSettingsNav.cshtml
@{
    Layout = "";
}
@*
    <div id="settings" class="btn-group">
        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-cog"></i>
        </a>
        <ul class="dropdown-menu pull-right">
            <li>
                <label class="checkbox toggle-bg">
                    <input type="checkbox" /> <span class="copy">Hide Background</span>
                </label>
            </li>
        </ul>
    </div>
*@

MinecraftCubed.Web/Views/User/LoginButton.cshtml
@using MinecraftCubed.Common
@{
    Layout = "";
}

<a class="btn btn-primary btn-large" href="@Settings.Website?open=login" onclick="Auth.ShowLoginModal(); return false;"><i class="fa fa-user"></i> Login</a>

MinecraftCubed.Web/Views/User/SettingsNav.cshtml
@{
    Layout = "";
}
@*

    <div id="settings" class="btn-group">
        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-cog"></i>
        </a>
        <ul class="dropdown-menu pull-right">
            <li>
                <label class="checkbox toggle-bg">
                    <input type="checkbox" /> <span class="copy">Hide Background</span>
                </label>
            </li>
            <li>
                <label class="checkbox toggle-flip">
                    <input type="checkbox" /> <span class="copy">Auto Flip Cards</span>
                </label>
            </li>
            <li>
                <label class="checkbox toggle-unflip">
                    <input type="checkbox" /> <span class="copy">Auto UnFlip Cards</span>
                </label>
            </li>
        </ul>
    </div>

*@

MinecraftCubed.Web/Views/User/UserNav.cshtml
@model MinecraftCubed.Web.ViewModels.User_.UserNavModel
@using MinecraftCubed.Static
@using MinecraftCubed.Web.Mvc.HtmlHelpers
@{
    Layout = "";
}

<ul id="user-menu" class="nav nav-pills">
    <li class="dropdown">
        <a id="nav-dropdown" class="dropdown-toggle" data-toggle="dropdown">
            <img class="face" src="@Model.FaceUrl" /><b class="caret"></b>
        </a>
        <ul class="dropdown-menu pull-right">
            @if (Html.HasRole(UserRole.SysAdmin))
            {
                <li>
                    <a href="@Url.Action("Index", "Admin")"><i class="fa fa-fw fa-university"></i> Admin Panel</a>
                </li>
            }

            @if (Html.HasRole(UserRole.Editor))
            {
                <li>
                    <a href="@Url.Action("Index", "Stub")"><i class="fa fa-fw fa-database"></i> Stub Manager</a>
                </li>

                <li class="divider"></li>
            }
            
            @if (Model.ManagedServers.Count > 1)
            {
                <li class="dropdown-submenu">
                    <a onclick="return false"><i class="fa fa-fw fa-th-large"></i>View Servers</a>
                    <ul class="dropdown-menu">

                        @foreach (var server in Model.ManagedServers)
                        {
                            <li>
                                <a href="@Url.Action("Index", "Server", new { identifier = server.Identifier })">@server.Name</a>
                            </li>
                        }
                    </ul>
                </li>
            }
            else if (Model.ManagedServers.Count == 1)
            {
                <li>
                    <a href="@Url.Action("Index", "Server", new { identifier = Model.ManagedServers.First().Identifier })"><i class="fa fa-fw fa-th-large"></i>View Server</a>
                </li>
            }
            
            @if (Model.ManagedServers.Count > 1)
            {
                <li class="dropdown-submenu">
                    <a onclick="return false"><i class="fa fa-fw fa-edit"></i>Manage Servers</a>
                    <ul class="dropdown-menu">

                        @foreach (var server in Model.ManagedServers)
                        {
                            <li>
                                <a href="@Url.Action("Index", "EditServer", new { identifier = server.Identifier })">@server.Name</a>
                            </li>
                        }
                    </ul>
                </li>
            }
            else if (Model.ManagedServers.Count == 1)
            {
                <li>
                    <a href="@Url.Action("Index", "EditServer", new { identifier = Model.ManagedServers.First().Identifier })"><i class="fa fa-fw fa-edit"></i>Manage Server</a>
                </li>
            }

            @if (Model.ManagedServers.Count > 0)
            {

                if (Model.ManagedEvents.Count > 1)
                {
                    <li class="dropdown-submenu">
                        <a onclick=" return false "><i class="fa fa-fw fa-edit"></i>Manage Events</a>
                        <ul class="dropdown-menu">

                            @foreach (var eve in Model.ManagedEvents)
                            {
                                <li>
                                    <a href="@Url.Action("Index", "EditEvent", new {eventIdentifier = eve.Identifier})">@eve.Name</a>
                                </li>
                            }
                        </ul>
                    </li>
                }
                else if (Model.ManagedEvents.Count == 1)
                {
                    <li>
                        <a href="@Url.Action("Index", "EditEvent", new { eventIdentifier = Model.ManagedEvents.First().Identifier })"><i class="fa fa-fw fa-edit"></i>Manage Event</a>
                    </li>
                }
            }

            <li class="divider"></li>

            <li>
                <a href="@Url.Action("Index", "Account")"><i class="fa fa-fw fa-cog"></i>Preferences</a>
            </li>
            <li>
                <a href="@Url.Action("Logout", "Auth")" onclick="Auth.Logout()"><i class="fa fa-fw fa-sign-out"></i>Logout</a>
            </li>
        </ul>
    </li>
</ul>